export * from './HomeTemplate';
export * from './CategoryTemplate';
export * from './NewComicTemplate';
export * from './UpdatingTemplate';
export * from './CompleteTemplate';
export * from './ComicByCategory.tsx';
export * from './ComicTemplate.tsx';
export * from './ChapterTemplate.tsx';
export * from './ContactTemplete.tsx';
export * from './ComicSearch.tsx'